title: Thomas Greenhill
description: > # this means to ignore newlines until "baseurl:"
  Thomas Greenhill's passion projects and engineering portfolio.
permalink: ':title/'
baseurl: "https://www.teawiththomas.com/" # the subpath of your site, e.g. /blog
# /flexible-jekyll
url: "www.teawiththomas.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Thomas V. Greenhill # add your name
author-img: TVG.jpg # add your photo
about-author: Welcome to my portfolio! I'm a fourth year double major in aerospace and mechanical engineering at UC Davis. <br /> <br /> I won the US Gliding Junior National Champion title in 2019 and ranked 18th in the world for gliding (average speed, general age category) in 2020. <br /> <br />I'm extremely passionate about system dynamics and control, and I eventually plan to pursue a graduate degree in mechatronics and control systems engineering. <br /> <br />If there's one thing I want you to know about me, it's that I'm very motivated by challenging problems which require hard work and attention to detail. I'm very good at approaching difficult problems with a strong desire to learn and an ability to come up with simple, elegant solutions! # add description

# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-olc: 
social-github: ThomasGreenhill # add your Github handle
social-linkedin: thomas-greenhill-48b100129 # add your Linkedin handle
social-email: thomasvgreenhill@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
